services:
  collector:
    container_name: trends_collector
    image: python:latest
    depends_on:
      - "redis"
    volumes:
      - ./:/collector-dir
    command: bash -c "mkdir -p /collector-dir/output ; apt-get update -y && apt-get upgrade -y ; python -m pip install --upgrade pip ; pip install redis pandas pytrends pyyaml ; bash" 
    stdin_open: true
    tty: true     
  redis:
    container_name: trends_redis
    image: redis:latest
    volumes:
      - ./output:/output/
      - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]