services:
  collector:
    container_name: trends_collector
    build:
      dockerfile: dockerfile
      context: .
    depends_on:
      - "redis"
    volumes:
      - ./output:/output
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
  redis:
    container_name: trends_redis
    image: redis:latest
    volumes:
      - ./output:/redis/
      - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]